server:
  port: 8081 # Importante: Puerto distinto a Keycloak

spring:
  application:
    name: ms-usuarios

  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    # open-in-view: false # Descomenta esto para quitar la otra advertencia amarilla
    hibernate:
      ddl-auto: update # CAMBIO CLAVE: Esto fuerza a borrar y crear tablas al iniciar
    properties:
      # Borra la linea del dialecto, Hibernate 7 es inteligente y lo detecta solo
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Esta es la URL magica para que Spring encuentre el JwtDecoder
          issuer-uri: http://localhost:8080/realms/BarberiaRealm
          jwk-set-uri: http://localhost:8080/realms/BarberiaRealm/protocol/openid-connect/certs

# Configuracion personalizada para administrar Keycloak
keycloak:
  server-url: http://localhost:8080
  realm: BarberiaRealm
  admin-client-id: barberia-backend-client
  admin-client-secret: CfWR97yuEzCoiKl2qWMPVezXrv6mUD03 # Pegalo aqui!
